// <auto-generated />
namespace _1811062489_PhamCongMinh_Tuan3.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class KhoitaoModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(KhoitaoModel));
        
        string IMigrationMetadata.Id
        {
            get { return "202106250311370_KhoitaoModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
